
services:

  hexo:
    image: node:24
    working_dir: /app
    command: sh -c "npm install -g hexo-cli && sleep infinity"
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    restart: unless-stopped
    environment:
      - NODE_ENV=development
