
services:

  hexo:
    image: node:24
    working_dir: /app/Hexo
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    command:  bash -c "npm install && hexo server -p 4000 && sleep infinity"